export const SITES = {
  AL: "Acid-Lounge",
  AR: "AlphaRatio",
  FF: "FunFile",
  IPT: "IPTorrents",
  ME: "Milkie",
  nC: "nCore",
  PTM: "PreToMe",
  RTT: "RevolutionTT",
  SBS: "SuperBits",
  SPC: "Speed.cd",
  TD: "TorrentDay",
  TL: "TorrentLeech",
  TN: "",
  TS: "TorrentSeeds",
  Tby: "TorrentBytes",
  XS: "XSpeeds",
};
